//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjManAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int task_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> status { get; set; }
        public string Tasks { get; set; }
    }
}
