//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjManAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent_task
    {
        public int parent_id { get; set; }
        public string parent_task1 { get; set; }
    }
}
